# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("New Year Tasks")
        Dialog.resize(702, 584)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(30, 130, 271, 341))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setGeometry(QtCore.QRect(390, 130, 271, 341))
        self.listWidget_2.setObjectName("listWidget_2")
        self.good = QtWidgets.QLabel(Dialog)
        self.good.setGeometry(QtCore.QRect(480, 60, 211, 101))
        self.good.setObjectName("good")
        self.bad = QtWidgets.QLabel(Dialog)
        self.bad.setGeometry(QtCore.QRect(100, 60, 161, 91))
        self.bad.setObjectName("bad")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(300, 0, 91, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_button = QtWidgets.QPushButton(self.widget)
        self.add_button.setObjectName("add_button")
        self.verticalLayout.addWidget(self.add_button)
        self.remove_button = QtWidgets.QPushButton(self.widget)
        self.remove_button.setObjectName("remove_button")
        self.verticalLayout.addWidget(self.remove_button)
        self.move_button = QtWidgets.QPushButton(self.widget)
        self.move_button.setObjectName("move_button")
        self.verticalLayout.addWidget(self.move_button)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.good.setText(_translate("Dialog", "Выполненые задачи"))
        self.bad.setText(_translate("Dialog", "Активные задачи"))
        self.add_button.setText(_translate("Dialog", "Добавить"))
        self.remove_button.setText(_translate("Dialog", "Убрать"))
        self.move_button.setText(_translate("Dialog", "Переместить"))
